[build-system]
requires = ["setuptools>=52", "wheel", "scikit-build", "cmake>=3.17", "ninja"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
# If there are data files included in your packages that need to be
# installed, specify them here.
package-data = {"cuda_mock" = ["*.so"]}
